resolver: lts-7.11
packages:
  - '.'
  - '../..'
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
extra-deps:
  - monad-supply-0.6
  - amazonka-dynamodb-1.4.5
  - amazonka-core-1.4.5
  - amazonka-1.4.5
  - http-conduit-2.2.3
  - http-client-0.5.4
  - http-client-tls-0.3.3
